### ISSUE TITLE
Create a personal access token for 2 factor authentication (to use in place of a password with the command line)

### ISSUE THREAD

**Issue by KathiePardoe-pi** [propellerindustries/GitHub#3]
Personal access tokens (PATs) are an alternative to using passwords for authentication to GitHub when using the GitHub API or the command line. 

Creating a personal access token to use in place of a password with the command line or with the API:
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

**Comment by robcrock** [comment]
@KathiePardoe-pi would you like me to add this to the Q&A section of the Wiki or can you?

Here's a link to that page: https://github.com/propellerindustries/GitHub/wiki/q&a

**Comment by KathiePardoe-pi** [comment]
added to the Wiki
